#!/bin/bash
echo "*********************************************************"
echo "Running git pre-commit hook. Running Detekt... "
echo "*********************************************************"

# run detekt
./gradlew detekt

status=$?

if [ "$status" = 0 ] ; then
    echo "Static analysis found no problems."
    #Exit
    exit 0
else
    echo "*********************************************************"
    echo 1>&2 "Detekt found problems."
    echo "*********************************************************"
    #Exit
    exit 1
fi
